import type { WorkflowDoc } from '@/types';

export const seedDoc: WorkflowDoc = {
  version: 1,
  rootFlowId: 'flow-root',
  flows: [
    {
      id: 'flow-root',
      name: 'Customer Onboarding',
      description: 'End-to-end process for onboarding a new B2B customer from signed contract to first value delivery.',
      parentFlowId: null,
      companyName: 'ACME Ltd',
      departmentId: 'dept-cs',
    },
    {
      id: 'flow-billing',
      name: 'Billing Setup',
      description: 'Configure the customer billing account, payment method, and first invoice in Stripe.',
      parentFlowId: 'flow-root',
      departmentId: 'dept-finance',
    },
    {
      id: 'flow-provisioning',
      name: 'Account Provisioning',
      description: 'Create user accounts, assign licences, and configure SSO.',
      parentFlowId: 'flow-root',
      departmentId: 'dept-it',
    },
  ],
  frequencies: [
    { id: 'freq-new-customer', label: 'per new customer', occurrencesPerMonth: 16 },
    { id: 'freq-new-customer-ent', label: 'per new customer (enterprise)', occurrencesPerMonth: 4 },
  ],
  personas: [
    { id: 'persona-csm', role: 'Customer Success Manager', workerCount: 3, avgWeeklyHours: 40 },
    { id: 'persona-salesops', role: 'Sales Operations', workerCount: 2, avgWeeklyHours: 40 },
    { id: 'persona-finance', role: 'Finance Analyst', workerCount: 2, avgWeeklyHours: 40 },
    { id: 'persona-itops', role: 'IT Operations', workerCount: 3, avgWeeklyHours: 40 },
  ],
  departments: [
    { id: 'dept-cs', name: 'Customer Success' },
    { id: 'dept-finance', name: 'Finance' },
    { id: 'dept-it', name: 'IT Operations' },
  ],
  nodes: [
    // ── Root flow nodes ───────────────────────────────────────────────────────
    {
      id: 'n-start',
      type: 'start',
      position: { x: 0, y: 180 },
      flowId: 'flow-root',
      data: {
        type: 'start',
        name: 'Start',
        description: 'A new B2B customer deal is closed.',
      },
    },
    {
      id: 'n-contract',
      type: 'task',
      position: { x: 180, y: 120 },
      flowId: 'flow-root',
      data: {
        type: 'task',
        name: 'Receive signed contract',
        description: 'CS team receives the countersigned MSA from the customer via email. Document saved to Google Drive.',
        personaId: 'persona-csm',
        humanMinutesPerRun: 15,
        frequencyId: 'freq-new-customer',
        tools: ['Gmail', 'Google Drive'],
        inputs: ['Countersigned MSA (PDF)'],
        outputs: ['Contract stored in Drive', 'Opportunity updated in Salesforce'],
        dataSources: ['Gmail', 'Salesforce CRM'],
        isManual: true,
        dataDriven: false,
        painPoints: 'Manually tracking whether contracts have been received is error-prone; deals occasionally fall through the cracks.',
      },
    },
    {
      id: 'n-decision-approved',
      type: 'decision',
      position: { x: 470, y: 140 },
      flowId: 'flow-root',
      data: {
        type: 'decision',
        name: 'Contract approved?',
        description: 'Legal team reviews the signed MSA for compliance before proceeding.',
        informationCompleteness: 'partial',
        decisionBasis: 'experience',
        reversibility: 'hard_to_reverse',
        costOfError: 'high',
        historicalDataExists: true,
        outcomeMeasured: true,
        outcomeDataSource: 'Salesforce closed-won/lost history',
      },
    },
    {
      id: 'n-end-rejected',
      type: 'end',
      position: { x: 660, y: 360 },
      flowId: 'flow-root',
      data: {
        type: 'end',
        name: 'Contract rejected',
        description: 'Contract returned to customer for revision; process stops here.',
      },
    },
    {
      id: 'n-crm',
      type: 'task',
      position: { x: 660, y: 120 },
      flowId: 'flow-root',
      data: {
        type: 'task',
        name: 'Create CRM record',
        description: 'Sales ops creates or updates the Account/Opportunity in Salesforce and fills in contract details.',
        personaId: 'persona-salesops',
        humanMinutesPerRun: 20,
        frequencyId: 'freq-new-customer',
        tools: ['Salesforce'],
        inputs: ['Contract details', 'Customer info'],
        outputs: ['Salesforce Account', 'Salesforce Opportunity (Closed Won)'],
        dataSources: ['Salesforce CRM', 'Contract PDF'],
        isManual: true,
        dataDriven: true,
        painPoints: 'Data entry is repetitive and frequently produces inconsistent field formats. Takes ~20 min per deal.',
      },
    },
    {
      id: 'n-billing',
      type: 'flow',
      position: { x: 950, y: 70 },
      flowId: 'flow-root',
      data: {
        type: 'flow',
        name: 'Billing Setup',
        childFlowId: 'flow-billing',
        description: 'Configure Stripe billing account and send first invoice.',
        departmentId: 'dept-finance',
      },
    },
    {
      id: 'n-provisioning',
      type: 'flow',
      position: { x: 950, y: 250 },
      flowId: 'flow-root',
      data: {
        type: 'flow',
        name: 'Account Provisioning',
        childFlowId: 'flow-provisioning',
        description: 'Create user accounts, assign licences, configure SSO.',
        departmentId: 'dept-it',
      },
    },
    {
      id: 'n-kickoff',
      type: 'task',
      position: { x: 1240, y: 160 },
      flowId: 'flow-root',
      data: {
        type: 'task',
        name: 'Send kickoff email',
        description: 'CS Manager sends a personalised kickoff email to the customer contact with onboarding guide and next steps.',
        personaId: 'persona-csm',
        humanMinutesPerRun: 30,
        frequencyId: 'freq-new-customer',
        tools: ['Gmail', 'Notion (template library)'],
        inputs: ['Customer name', 'CSM name', 'Onboarding guide PDF'],
        outputs: ['Kickoff email sent', 'Follow-up calendar invite'],
        dataSources: ['Salesforce CRM', 'Notion'],
        isManual: true,
        dataDriven: false,
        painPoints: 'Email is personalised from a template but takes ~30 min due to copy-pasting from multiple sources.',
      },
    },
    {
      id: 'n-end-complete',
      type: 'end',
      position: { x: 1530, y: 180 },
      flowId: 'flow-root',
      data: {
        type: 'end',
        name: 'Onboarding complete',
        description: 'Customer is live, accounts provisioned, billing active, and kickoff sent.',
      },
    },
    {
      id: 'n-end-billing-blocked',
      type: 'end',
      position: { x: 1240, y: -40 },
      flowId: 'flow-root',
      data: {
        type: 'end',
        name: 'Billing blocked',
        description: 'Billing setup could not complete; finance picks this up before onboarding continues.',
      },
    },

    // ── Billing Setup sub-flow nodes ─────────────────────────────────────────
    {
      id: 'n-billing-start',
      type: 'start',
      position: { x: -160, y: 96 },
      flowId: 'flow-billing',
      data: {
        type: 'start',
        name: 'Entry',
        description: 'Entered from the Billing Setup sub-flow node in the parent flow.',
      },
    },
    {
      id: 'n-stripe-customer',
      type: 'task',
      position: { x: 60, y: 80 },
      flowId: 'flow-billing',
      data: {
        type: 'task',
        name: 'Create Stripe customer',
        description: 'Finance team manually creates a Stripe customer record and attaches the card/bank mandate.',
        personaId: 'persona-finance',
        humanMinutesPerRun: 10,
        frequencyId: 'freq-new-customer',
        tools: ['Stripe Dashboard'],
        inputs: ['Customer name', 'Billing email', 'Payment method'],
        outputs: ['Stripe customer ID'],
        dataSources: ['Salesforce CRM'],
        isManual: true,
        dataDriven: false,
        painPoints: 'Switching between Salesforce and Stripe is tedious; easy to mis-type billing details.',
      },
    },
    {
      id: 'n-subscription',
      type: 'task',
      position: { x: 340, y: 80 },
      flowId: 'flow-billing',
      data: {
        type: 'task',
        name: 'Set up subscription',
        description: 'Finance configures the subscription plan, discount codes, and billing cycle in Stripe.',
        personaId: 'persona-finance',
        humanMinutesPerRun: 15,
        frequencyId: 'freq-new-customer',
        tools: ['Stripe Dashboard'],
        inputs: ['Stripe customer ID', 'Contract pricing tier', 'Discount codes'],
        outputs: ['Active Stripe subscription'],
        dataSources: ['Salesforce CRM', 'Stripe'],
        isManual: true,
        dataDriven: true,
        painPoints: 'Pricing tier must be manually looked up in Salesforce contract. No automated mapping exists.',
        inputAccessibility: 'search',
        searchTime: 5,
      },
    },
    {
      id: 'n-invoice',
      type: 'task',
      position: { x: 620, y: 80 },
      flowId: 'flow-billing',
      data: {
        type: 'task',
        name: 'Send first invoice',
        description: 'Finance generates and sends the first invoice manually via Stripe, then notifies the customer by email.',
        personaId: 'persona-finance',
        humanMinutesPerRun: 10,
        frequencyId: 'freq-new-customer',
        tools: ['Stripe Dashboard', 'Gmail'],
        inputs: ['Active subscription'],
        outputs: ['Invoice sent', 'Payment confirmation'],
        dataSources: ['Stripe'],
        isManual: false,
        dataDriven: false,
        painPoints: 'Invoice sending could be automated in Stripe; manual step adds a day of lag.',
      },
    },
    {
      id: 'n-billing-decision',
      type: 'decision',
      position: { x: 890, y: 40 },
      flowId: 'flow-billing',
      data: {
        type: 'decision',
        name: 'Payment received?',
        description: 'Finance checks whether the first invoice cleared before handing back to onboarding.',
        informationCompleteness: 'full',
        decisionBasis: 'rules',
      },
    },
    {
      id: 'n-billing-end',
      type: 'end',
      position: { x: 1120, y: -30 },
      flowId: 'flow-billing',
      data: {
        type: 'end',
        name: 'Billing active',
        description: 'Invoice cleared; billing setup complete and control returns to the parent flow.',
      },
    },
    {
      id: 'n-billing-end-failed',
      type: 'end',
      position: { x: 1120, y: 230 },
      flowId: 'flow-billing',
      data: {
        type: 'end',
        name: 'Payment failed',
        description: 'Card declined or invoice unpaid; control returns to the parent flow on this exit.',
      },
    },
    // A retry loop: an unpaid invoice sends the run back to re-invoice rather than
    // straight to the "Payment failed" exit. See the e-chase-* edges below — the loop is
    // {n-invoice, n-billing-decision, n-chase-payment, n-chase-escalate}, guarded by both
    // decisions (each can still reach one of the two exits above).
    {
      id: 'n-chase-payment',
      type: 'task',
      position: { x: 620, y: 320 },
      flowId: 'flow-billing',
      data: {
        type: 'task',
        name: 'Chase payment',
        description: 'Finance follows up with the customer by phone or email to resolve the declined card or unpaid invoice.',
        personaId: 'persona-finance',
        humanMinutesPerRun: 15,
        frequencyId: 'freq-new-customer',
        tools: ['Stripe Dashboard', 'Gmail', 'Phone'],
        inputs: ['Payment failed reason'],
        outputs: ['Updated payment method or promise to pay'],
        dataSources: ['Stripe'],
        isManual: true,
        dataDriven: false,
        painPoints: 'Chasing payment is repetitive and manual; no automated dunning sequence exists.',
        inputAccessibility: 'search',
        searchTime: 5,
      },
    },
    {
      id: 'n-chase-escalate',
      type: 'decision',
      position: { x: 890, y: 330 },
      flowId: 'flow-billing',
      data: {
        type: 'decision',
        name: 'Escalate to collections?',
        description: 'Finance decides whether to escalate an unresolved payment to collections or try invoicing again.',
        informationCompleteness: 'partial',
        decisionBasis: 'experience',
      },
    },

    // ── Account Provisioning sub-flow nodes ──────────────────────────────────
    {
      id: 'n-provisioning-start',
      type: 'start',
      position: { x: -160, y: 96 },
      flowId: 'flow-provisioning',
      data: {
        type: 'start',
        name: 'Entry',
        description: 'Entered from the Account Provisioning sub-flow node in the parent flow.',
      },
    },
    {
      id: 'n-create-users',
      type: 'task',
      position: { x: 60, y: 80 },
      flowId: 'flow-provisioning',
      data: {
        type: 'task',
        name: 'Create user accounts',
        description: 'IT ops creates individual user accounts in the identity provider for each named user on the contract.',
        personaId: 'persona-itops',
        humanMinutesPerRun: 45,
        frequencyId: 'freq-new-customer',
        tools: ['Okta', 'Google Admin'],
        inputs: ['User list (spreadsheet)', 'Domain info'],
        outputs: ['User accounts in Okta', 'Welcome emails queued'],
        dataSources: ['Customer-supplied spreadsheet', 'Okta'],
        isManual: true,
        dataDriven: true,
        painPoints: 'Creating 10-50 users per customer is entirely manual and takes 45–90 min with current tooling.',
      },
    },
    {
      id: 'n-sso',
      type: 'task',
      position: { x: 340, y: 80 },
      flowId: 'flow-provisioning',
      data: {
        type: 'task',
        name: 'Configure SSO',
        description: 'IT ops configures SAML/OIDC SSO for the customer tenant, coordinating with customer IT team.',
        personaId: 'persona-itops',
        humanMinutesPerRun: 60,
        frequencyId: 'freq-new-customer-ent',
        tools: ['Okta', 'Customer IdP'],
        inputs: ['Customer IdP metadata', 'SAML certificate'],
        outputs: ['SSO configured and tested'],
        dataSources: ['Okta', 'Customer IT docs'],
        isManual: true,
        dataDriven: false,
        painPoints: 'Back-and-forth with customer IT. Inconsistent customer documentation causes repeated clarifications.',
        inputAccessibility: 'ask',
        searchTime: 30,
        inputSource: 'Senior IT engineer + customer IT team (no shared runbook)',
        knowledgeCaptured: false,
        expertiseLevel: 'senior',
      },
    },
    {
      id: 'n-welcome',
      type: 'task',
      position: { x: 620, y: 80 },
      flowId: 'flow-provisioning',
      data: {
        type: 'task',
        name: 'Send welcome credentials',
        description: 'IT ops sends each user their temporary credentials and onboarding guide link via email.',
        personaId: 'persona-itops',
        humanMinutesPerRun: 20,
        frequencyId: 'freq-new-customer',
        tools: ['Gmail', 'Okta'],
        inputs: ['User list', 'Onboarding guide URL'],
        outputs: ['Welcome emails sent'],
        dataSources: ['Okta', 'Notion'],
        isManual: true,
        dataDriven: false,
        painPoints: 'Sending individual emails is slow; no bulk mail capability without a marketing tool.',
      },
    },
    {
      id: 'n-provisioning-end',
      type: 'end',
      position: { x: 880, y: 96 },
      flowId: 'flow-provisioning',
      data: {
        type: 'end',
        name: 'Exit',
        description: 'Provisioning complete; control returns to the parent flow.',
      },
    },
  ],
  edges: [
    // Root flow edges
    { id: 'e-start', source: 'n-start', target: 'n-contract', flowId: 'flow-root' },
    { id: 'e-1', source: 'n-contract', target: 'n-decision-approved', flowId: 'flow-root' },
    {
      id: 'e-decision-yes',
      source: 'n-decision-approved',
      target: 'n-crm',
      sourceHandle: 'yes',
      label: 'Yes',
      data: { branch: 'yes' },
      flowId: 'flow-root',
    },
    {
      id: 'e-decision-no',
      source: 'n-decision-approved',
      target: 'n-end-rejected',
      sourceHandle: 'no',
      label: 'No',
      data: { branch: 'no' },
      flowId: 'flow-root',
    },
    { id: 'e-2', source: 'n-crm', target: 'n-billing', flowId: 'flow-root' },
    { id: 'e-3', source: 'n-crm', target: 'n-provisioning', flowId: 'flow-root' },
    // The Billing Setup sub-flow has two named exits, so its edges name which one they leave from.
    {
      id: 'e-4',
      source: 'n-billing',
      target: 'n-kickoff',
      sourceHandle: 'n-billing-end',
      data: { exit: 'Billing active' },
      flowId: 'flow-root',
    },
    {
      id: 'e-4-failed',
      source: 'n-billing',
      target: 'n-end-billing-blocked',
      sourceHandle: 'n-billing-end-failed',
      data: { exit: 'Payment failed' },
      flowId: 'flow-root',
    },
    {
      id: 'e-5',
      source: 'n-provisioning',
      target: 'n-kickoff',
      sourceHandle: 'n-provisioning-end',
      data: { exit: 'Exit' },
      flowId: 'flow-root',
    },
    { id: 'e-end', source: 'n-kickoff', target: 'n-end-complete', flowId: 'flow-root' },
    // Billing sub-flow
    { id: 'e-b0', source: 'n-billing-start', target: 'n-stripe-customer', flowId: 'flow-billing' },
    { id: 'e-b1', source: 'n-stripe-customer', target: 'n-subscription', flowId: 'flow-billing' },
    { id: 'e-b2', source: 'n-subscription', target: 'n-invoice', flowId: 'flow-billing' },
    { id: 'e-b3', source: 'n-invoice', target: 'n-billing-decision', flowId: 'flow-billing' },
    // The decision's branches land on the two exits, which surface as labelled exit points
    // on the "Billing Setup" node in the root flow.
    {
      id: 'e-b4-yes',
      source: 'n-billing-decision',
      target: 'n-billing-end',
      sourceHandle: 'yes',
      label: 'Yes',
      data: { branch: 'yes' },
      flowId: 'flow-billing',
    },
    {
      id: 'e-b4-no',
      source: 'n-billing-decision',
      target: 'n-chase-payment',
      sourceHandle: 'no',
      label: 'No',
      data: { branch: 'no' },
      flowId: 'flow-billing',
    },
    { id: 'e-chase-0', source: 'n-chase-payment', target: 'n-chase-escalate', flowId: 'flow-billing' },
    {
      id: 'e-chase-yes',
      source: 'n-chase-escalate',
      target: 'n-billing-end-failed',
      sourceHandle: 'yes',
      label: 'Yes',
      data: { branch: 'yes' },
      flowId: 'flow-billing',
    },
    // The back edge: unresolved but not yet worth escalating, so the run goes back to
    // re-invoice. `retryRatePct` is the share of billing runs Finance expects to take
    // this path — the analysis prompt uses it to scale a looped task's time-saved figure.
    {
      id: 'e-chase-no',
      source: 'n-chase-escalate',
      target: 'n-invoice',
      sourceHandle: 'no',
      label: 'No',
      data: { branch: 'no', retryRatePct: 20 },
      flowId: 'flow-billing',
    },
    // Provisioning sub-flow
    { id: 'e-p0', source: 'n-provisioning-start', target: 'n-create-users', flowId: 'flow-provisioning' },
    { id: 'e-p1', source: 'n-create-users', target: 'n-sso', flowId: 'flow-provisioning' },
    { id: 'e-p2', source: 'n-sso', target: 'n-welcome', flowId: 'flow-provisioning' },
    { id: 'e-p3', source: 'n-welcome', target: 'n-provisioning-end', flowId: 'flow-provisioning' },
  ],
};
