import type { WorkflowDoc } from '@/types';

export const seedDoc: WorkflowDoc = {
  version: 1,
  rootFlowId: 'flow-root',
  flows: [
    {
      id: 'flow-root',
      name: 'Customer Onboarding',
      description: 'End-to-end process for onboarding a new B2B customer from signed contract to first value delivery.',
      parentFlowId: null,
    },
    {
      id: 'flow-billing',
      name: 'Billing Setup',
      description: 'Configure the customer billing account, payment method, and first invoice in Stripe.',
      parentFlowId: 'flow-root',
    },
    {
      id: 'flow-provisioning',
      name: 'Account Provisioning',
      description: 'Create user accounts, assign licences, and configure SSO.',
      parentFlowId: 'flow-root',
    },
  ],
  nodes: [
    // ── Root flow nodes ───────────────────────────────────────────────────────
    {
      id: 'n-contract',
      type: 'task',
      position: { x: 60, y: 80 },
      flowId: 'flow-root',
      data: {
        type: 'task',
        name: 'Receive signed contract',
        description: 'CS team receives the countersigned MSA from the customer via email. Document saved to Google Drive.',
        ownerRole: 'Customer Success Manager',
        status: 'active',
        humanMinutesPerRun: 15,
        frequency: 'per new customer',
        tools: ['Gmail', 'Google Drive'],
        inputs: ['Countersigned MSA (PDF)'],
        outputs: ['Contract stored in Drive', 'Opportunity updated in Salesforce'],
        dataSources: ['Gmail', 'Salesforce CRM'],
        isManual: true,
        dataDriven: false,
        painPoints: 'Manually tracking whether contracts have been received is error-prone; deals occasionally fall through the cracks.',
      },
    },
    {
      id: 'n-crm',
      type: 'task',
      position: { x: 340, y: 80 },
      flowId: 'flow-root',
      data: {
        type: 'task',
        name: 'Create CRM record',
        description: 'Sales ops creates or updates the Account/Opportunity in Salesforce and fills in contract details.',
        ownerRole: 'Sales Operations',
        status: 'active',
        humanMinutesPerRun: 20,
        frequency: 'per new customer',
        tools: ['Salesforce'],
        inputs: ['Contract details', 'Customer info'],
        outputs: ['Salesforce Account', 'Salesforce Opportunity (Closed Won)'],
        dataSources: ['Salesforce CRM', 'Contract PDF'],
        isManual: true,
        dataDriven: true,
        painPoints: 'Data entry is repetitive and frequently produces inconsistent field formats. Takes ~20 min per deal.',
      },
    },
    {
      id: 'n-billing',
      type: 'flow',
      position: { x: 620, y: 80 },
      flowId: 'flow-root',
      data: {
        type: 'flow',
        name: 'Billing Setup',
        childFlowId: 'flow-billing',
        description: 'Configure Stripe billing account and send first invoice.',
      },
    },
    {
      id: 'n-provisioning',
      type: 'flow',
      position: { x: 340, y: 260 },
      flowId: 'flow-root',
      data: {
        type: 'flow',
        name: 'Account Provisioning',
        childFlowId: 'flow-provisioning',
        description: 'Create user accounts, assign licences, configure SSO.',
      },
    },
    {
      id: 'n-kickoff',
      type: 'task',
      position: { x: 620, y: 260 },
      flowId: 'flow-root',
      data: {
        type: 'task',
        name: 'Send kickoff email',
        description: 'CS Manager sends a personalised kickoff email to the customer contact with onboarding guide and next steps.',
        ownerRole: 'Customer Success Manager',
        status: 'active',
        humanMinutesPerRun: 30,
        frequency: 'per new customer',
        tools: ['Gmail', 'Notion (template library)'],
        inputs: ['Customer name', 'CSM name', 'Onboarding guide PDF'],
        outputs: ['Kickoff email sent', 'Follow-up calendar invite'],
        dataSources: ['Salesforce CRM', 'Notion'],
        isManual: true,
        dataDriven: false,
        painPoints: 'Email is personalised from a template but takes ~30 min due to copy-pasting from multiple sources.',
      },
    },

    // ── Billing Setup sub-flow nodes ─────────────────────────────────────────
    {
      id: 'n-stripe-customer',
      type: 'task',
      position: { x: 60, y: 80 },
      flowId: 'flow-billing',
      data: {
        type: 'task',
        name: 'Create Stripe customer',
        description: 'Finance team manually creates a Stripe customer record and attaches the card/bank mandate.',
        ownerRole: 'Finance Analyst',
        status: 'active',
        humanMinutesPerRun: 10,
        frequency: 'per new customer',
        tools: ['Stripe Dashboard'],
        inputs: ['Customer name', 'Billing email', 'Payment method'],
        outputs: ['Stripe customer ID'],
        dataSources: ['Salesforce CRM'],
        isManual: true,
        dataDriven: false,
        painPoints: 'Switching between Salesforce and Stripe is tedious; easy to mis-type billing details.',
      },
    },
    {
      id: 'n-subscription',
      type: 'task',
      position: { x: 340, y: 80 },
      flowId: 'flow-billing',
      data: {
        type: 'task',
        name: 'Set up subscription',
        description: 'Finance configures the subscription plan, discount codes, and billing cycle in Stripe.',
        ownerRole: 'Finance Analyst',
        status: 'active',
        humanMinutesPerRun: 15,
        frequency: 'per new customer',
        tools: ['Stripe Dashboard'],
        inputs: ['Stripe customer ID', 'Contract pricing tier', 'Discount codes'],
        outputs: ['Active Stripe subscription'],
        dataSources: ['Salesforce CRM', 'Stripe'],
        isManual: true,
        dataDriven: true,
        painPoints: 'Pricing tier must be manually looked up in Salesforce contract. No automated mapping exists.',
      },
    },
    {
      id: 'n-invoice',
      type: 'task',
      position: { x: 620, y: 80 },
      flowId: 'flow-billing',
      data: {
        type: 'task',
        name: 'Send first invoice',
        description: 'Finance generates and sends the first invoice manually via Stripe, then notifies the customer by email.',
        ownerRole: 'Finance Analyst',
        status: 'active',
        humanMinutesPerRun: 10,
        frequency: 'per new customer',
        tools: ['Stripe Dashboard', 'Gmail'],
        inputs: ['Active subscription'],
        outputs: ['Invoice sent', 'Payment confirmation'],
        dataSources: ['Stripe'],
        isManual: false,
        dataDriven: false,
        painPoints: 'Invoice sending could be automated in Stripe; manual step adds a day of lag.',
      },
    },

    // ── Account Provisioning sub-flow nodes ──────────────────────────────────
    {
      id: 'n-create-users',
      type: 'task',
      position: { x: 60, y: 80 },
      flowId: 'flow-provisioning',
      data: {
        type: 'task',
        name: 'Create user accounts',
        description: 'IT ops creates individual user accounts in the identity provider for each named user on the contract.',
        ownerRole: 'IT Operations',
        status: 'active',
        humanMinutesPerRun: 45,
        frequency: 'per new customer',
        tools: ['Okta', 'Google Admin'],
        inputs: ['User list (spreadsheet)', 'Domain info'],
        outputs: ['User accounts in Okta', 'Welcome emails queued'],
        dataSources: ['Customer-supplied spreadsheet', 'Okta'],
        isManual: true,
        dataDriven: true,
        painPoints: 'Creating 10-50 users per customer is entirely manual and takes 45–90 min with current tooling.',
      },
    },
    {
      id: 'n-sso',
      type: 'task',
      position: { x: 340, y: 80 },
      flowId: 'flow-provisioning',
      data: {
        type: 'task',
        name: 'Configure SSO',
        description: 'IT ops configures SAML/OIDC SSO for the customer tenant, coordinating with customer IT team.',
        ownerRole: 'IT Operations',
        status: 'active',
        humanMinutesPerRun: 60,
        frequency: 'per new customer (enterprise)',
        tools: ['Okta', 'Customer IdP'],
        inputs: ['Customer IdP metadata', 'SAML certificate'],
        outputs: ['SSO configured and tested'],
        dataSources: ['Okta', 'Customer IT docs'],
        isManual: true,
        dataDriven: false,
        painPoints: 'Back-and-forth with customer IT. Inconsistent customer documentation causes repeated clarifications.',
      },
    },
    {
      id: 'n-welcome',
      type: 'task',
      position: { x: 620, y: 80 },
      flowId: 'flow-provisioning',
      data: {
        type: 'task',
        name: 'Send welcome credentials',
        description: 'IT ops sends each user their temporary credentials and onboarding guide link via email.',
        ownerRole: 'IT Operations',
        status: 'active',
        humanMinutesPerRun: 20,
        frequency: 'per new customer',
        tools: ['Gmail', 'Okta'],
        inputs: ['User list', 'Onboarding guide URL'],
        outputs: ['Welcome emails sent'],
        dataSources: ['Okta', 'Notion'],
        isManual: true,
        dataDriven: false,
        painPoints: 'Sending individual emails is slow; no bulk mail capability without a marketing tool.',
      },
    },
  ],
  edges: [
    // Root flow edges
    { id: 'e-1', source: 'n-contract', target: 'n-crm', flowId: 'flow-root' },
    { id: 'e-2', source: 'n-crm', target: 'n-billing', flowId: 'flow-root' },
    { id: 'e-3', source: 'n-crm', target: 'n-provisioning', flowId: 'flow-root' },
    { id: 'e-4', source: 'n-billing', target: 'n-kickoff', flowId: 'flow-root' },
    { id: 'e-5', source: 'n-provisioning', target: 'n-kickoff', flowId: 'flow-root' },
    // Billing sub-flow
    { id: 'e-b1', source: 'n-stripe-customer', target: 'n-subscription', flowId: 'flow-billing' },
    { id: 'e-b2', source: 'n-subscription', target: 'n-invoice', flowId: 'flow-billing' },
    // Provisioning sub-flow
    { id: 'e-p1', source: 'n-create-users', target: 'n-sso', flowId: 'flow-provisioning' },
    { id: 'e-p2', source: 'n-sso', target: 'n-welcome', flowId: 'flow-provisioning' },
  ],
};
